config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :show, :index, :update]
  root to: 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_one_attached :image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user, uniqueness: {scope: :book}
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def self.default_image
    @default_image ||= begin
      path = Rails.root.join('app', 'assets', 'images', 'default-image.jpg')
      unless ActiveStorage::Blob.exists?(filename: 'default-image.jpg')
        ActiveStorage::Blob.create_and_upload!(
          io: File.open(path),
          filename: 'default-image.jpg',
          content_type: 'image/jpeg'
        )
      end
      ActiveStorage::Blob.find_by(filename: 'default-image.jpg')
    end
  end

  def get_profile_image(width, height)
    if profile_image.attached?
      profile_image.variant(resize_to_limit: [width, height]).processed
    else
      # デフォルト画像のパスを直接指定
      ActionController::Base.helpers.asset_path('default-image.jpg')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:success] = "Signed in successfully."
    user_path(resource.id)
  end


  def after_sign_out_path_for(resource)
    flash[:success] = "Signed out successfully."
    root_path
  end

  def after_sign_up_path_for(resource)
    flash[:success] = "Welcome! You have signed up successfully."
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :set_book_comment, only: [:destroy]


  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def destroy
    if @book_comment && @book_comment.user == current_user
      @book_comment.destroy
      redirect_to book_path(@book_comment.book)
    else
      redirect_to books_path
    end
  end

  private

  def set_book_comment
    @book_comment = BookComment.find(params[:id])
  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: 'You have created book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @new_book = Book.new
    @user = @book.user
  end


  def edit
    @user = @book.user
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def ensure_correct_user
    redirect_to books_path unless @book.user == current_user
  end

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book: book)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book: book)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    redirect_to user_path(current_user) unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_form.html.erb
<div class="card mt-3">
  <div class="card-body">
    <h1 class="card-title">New book</h1>
    <%= form_with model: book, local: true do |f| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
          <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-3">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control", id: "book_title" %>
      </div>
      <div class="mb-3">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control", id: "book_opinion" %>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit 'Create Book', class: "btn btn-success w-100" %>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'users/flash' %>
<h1 class="text-center">Editing Book</h1>
<div style="display: flex; justify-content: center;">
  <div style="max-width: 600px; width: 100%;">
    <% if @book.errors.any? %>
      <%= @book.errors.count %> error prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_with model: @book do |f| %>
      <div style="margin-bottom: 1rem;">
        <h4>Title</h4>
        <%= f.text_field :title, style: "width: 100%;" %>
      </div>
      <div style="margin-bottom: 1rem;">
        <h4>Opinion</h4>
        <%= f.text_area :body, style: "width: 100%;" %>
      </div>
      <br>
      <%= f.submit 'Update Book', class: 'btn btn-success' %>
    <% end %>
    <br>
    <%= link_to 'Show', book_path(@book) %> |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-4">
  <div class="row">
    <!-- 左側のカラム -->
    <div class="col-md-3">
      <%= render partial: 'users/user_info', locals: { user: nil } %>
      <%= render 'book_form', book: @book %>
    </div>
    <!-- 右側のカラム -->
    <div class="col-md-8 offset-md-1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Books</h5>
          <table class="table">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Opinion</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(100, 100), alt: 'User profile image', class: 'img-thumbnail' %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td>
                  <% if book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorite_path(book), method: :delete, class: "text-danger" do %>
                        <i class="fa-solid fa-heart"></i> <%= book.favorites.count %>
                      <% end %>
                    </p>
                  <% else %>
                    <p>
                      <%= link_to book_favorite_path(book), method: :post, class: "text-muted" do %>
                        <i class="fa-regular fa-heart"></i> <%= book.favorites.count %>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <td>コメント数: <%= book.book_comments.count %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'users/flash' %>

<div class="container mt-4">
  <div class="row">
    <!-- 左側のカラム -->
    <div class="col-md-3">
      <%= render partial: 'users/user_info', locals: { user: @user } %>
      <%= render 'book_form', book: @new_book %>
    </div>
    <!-- 右側のカラム -->
    <div class="col-md-8 offset-md-1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Book detail</h5>
          <div class="d-flex align-items-center mb-3">
            <%= image_tag @book.user.get_profile_image(100, 100), class: "img-fluid rounded me-3" %>
            <div>
              <strong><%= @book.title %></strong>
              <span class="mx-3"><%= @book.body %></span>
              <% if @book.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success me-2" %>
                <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-danger" %>
              <% end %>
              <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorite_path(@book), method: :delete, class: "text-danger" do %>
                    <i class="fa-solid fa-heart"></i> <%= @book.favorites.count %>
                  <% end %>
              <% else %>
                  <%= link_to book_favorite_path(@book), method: :post, class: "text-muted" do %>
                    <i class="fa-regular fa-heart"></i> <%= @book.favorites.count %>
                  <% end %>
              <% end %>
              コメント数: <%= @book.book_comments.count %>
            </div>
          </div>
          <div>
            <%= link_to @book.user.name, user_path(@book.user.id) %>
          </div>
          <br>
          <div>
              <% @book.book_comments.each do |book_comment| %>
                <p><%= image_tag book_comment.user.get_profile_image(100, 100) %>
                <%= book_comment.comment %>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(@book, book_comment), method: :delete, class: "btn btn-danger btn-sm ms-2" %>
                <% end %>
                </p>
                <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
              <% end %>
            </div>
            <div>
            <%= form_with model: [@book, @book_comment] do |f| %>
              <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
              <%= f.submit "送信する" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1 class="text-center">
  Welcome to
  <i class="fa-solid fa-book"></i><b>Bookers!</b>
</h1>

app/views/homes/top.html.erb
<%= render 'users/flash' %>

<h1 class="text-center">
  Welcome to
  <i class="fa-solid fa-book"></i> <b>Bookers !!</b>
</h1>

<p class="text-center">
  In <i class="fa-solid fa-book"></i> <b>Bookers</b>,
</p>

<p class="text-center">
you can share and exchange your opinions , inpressions , and emotions
</p>

<div class="text-center">
  <%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-primary" %>
</div>

<div class="text-center">
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/337437c9ab.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-house mr-2"></i>
                  <%= link_to "Home", user_path(current_user), class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-users mr-2"></i>
                  <%= link_to "Users", users_path, class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-book-open mr-2"></i>
                  <%= link_to "Books", books_path, class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-right-from-bracket mr-2"></i>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark mb-0' %>
                </li>
              <% else %>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-house mr-2"></i>
                  <%= link_to "Home", "/", class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-link mr-2"></i>
                  <%= link_to "About", about_path, class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-user-plus mr-2"></i>
                  <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-dark mb-0' %>
                </li>
                <li class="nav-item d-flex align-items-center">
                  <i class="fa-solid fa-right-to-bracket"></i>
                  <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark mb-0' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/users/_user_info.html.erb
<% user_to_display = user || current_user %>
<div class="card-body">
  <div class="mb-3">
    <h2 class="card-title">User info</h2>
    <%= image_tag user_to_display.get_profile_image(100, 100) %>
  </div>
  <table class="table">
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user_to_display.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user_to_display.introduction %></th>
    </tr>
  </table>

  <%= link_to edit_user_path(user_to_display), class: "btn btn-outline-secondary w-100" do %>
    <i class="fa-solid fa-user-gear"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
  <%= render 'flash' %>


  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h3 class="text-center">User info</h3>

        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <strong><%= @user.errors.count %> error(s) prohibited this user from being saved:</strong>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_with model: @user, html: { class: 'form' } do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "名前" %>
          </div>

          <div class="form-group">
            <%= f.label :profile_image, 'Image' %>
            <%= f.file_field :profile_image, class: 'form-control-file', placeholder: "プロフィール画像", accept: "image/*" %>
          </div>

          <div class="form-group">
            <%= f.label :introduction, class: 'form-label' %>
            <%= f.text_field :introduction, autofocus: true, class: 'form-control', placeholder: "Introduction" %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Update User", class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<%= render 'flash' %>

<div class="container mt-4">
  <div class="row">
    <!-- 左側のカラム -->
    <div class="col-md-3">
      <%= render partial: 'user_info', locals: { user: nil } %>
      <%= render 'books/book_form', book: @book %>
    </div>
    <!-- 右側のカラム -->
    <div class="col-md-8 offset-md-1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Users</h5>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">image</th>
                <th scope="col">name</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= user.name %></td>
                <td><%= link_to 'Show', user_path(user.id), class: 'btn btn-primary' %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'flash' %>
<div class="container mt-4">
  <div class="row">
    <!-- 左側のカラム -->
    <div class="col-md-3">
      <%= render partial: 'user_info', locals: { user: @user } %>
      <%= render 'books/book_form', book: @book %>
    </div>
    <!-- 右側のカラム -->
    <div class="col-md-8 offset-md-1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Users</h5>
          <table class="table">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Opinion</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(100, 100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorite_path(book), method: :delete, class: "text-danger" do %>
                    <i class="fa-solid fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorite_path(book), method: :post, class: "text-muted" do %>
                    <i class="fa-regular fa-heart"></i> <%= book.favorites.count %>
                  <% end %>
                <% end %>
                </td>
                <td>コメント数: <%= book.book_comments.count %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>